### ISSUE TITLE
Updating to newest version

### ISSUE THREAD

**Issue by Iotheria** [zeddidragon/sgott#8]
Sorry,but I didn't know a better place to ask this.
I've tried for the life of me to find out myself how to update to the latest version from the July 24th build,and I can't seem to figure it out.
I'm not used to working with .js and .json files,so I basically have no idea what I'm doing.

**Comment by FIRE-AKA-DRAZN** [comment]
By latest version what do you mean exactly?

The current release is the most up to date release available.  I am currently working on a massive overhaul to all weapons but it is not ready yet, though I am getting close to being done.

There is another version of the sgottstrap.exe which is technically more up to date, but its only changes as far as I am aware are to how saves are handled.

Could you clarify if its my rebalance work or the sgottstrap.exe you are trying to update to?

**Comment by Iotheria** [comment]
I wasn't aware they were separate.
I was attempting to use your rebalance,but I thought you had to execute it through the July 24th,2018 "official release" .
If not,then how would one go about using it?

**Comment by FIRE-AKA-DRAZN** [comment]
The rebalance I am working on is essentially a collection of edited .json files for each weapon.  The coding involved only affected backend programs used to create those .jsons.

Installing my changes would be as simple as deleting everything inside the "SgottTemplate > weapon" folder provided in the current release and replacing it with my edited .jsons before running the sgottstrap.exe that came with that release.

However, as I said my rebalance work is not currently complete.  You can see my progress here: https://docs.google.com/spreadsheets/d/1ZcMneUf43jbCpKrSBvFZIcAq3WYP4qrdeNGkuvbcuco/edit?usp=sharing

That said I have uploaded a few rebalanced .jsons namely my changes to Limpet Guns.  However these are quite out of date now, but if you are interested in trying them you can find them inside the examples folder in the main repository.  

You can install these the same way i described above, but by **adding** them to the folder instead of deleting everything and replacing.

**Comment by Iotheria** [comment]
Alright! Thanks for the help. Looking forward to your release!
